---
HOSTS:
  centos7:
    roles:
      - agent
      - default
    platform: centos-7-x86_64
    hypervisor: vagrant
    box: centos/7
    # box_url: https://app.vagrantup.com/centos/boxes/7
    # htpps://puppetlabs/boxes/debian-8.2-64-nocm
    ip: 192.168.56.21
CONFIG:
  type: foss
